[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
solc = '0.8.24'
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/contracts/"
]

[profile.test]
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

[profile.coverage]
fuzz = { runs = 10000 }
invariant = { runs = 10000, depth = 15 }

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"


